name: xyz_open_ai
description:
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.1.5
dependencies:
  http:
  shelf_router:
  xml:
  html:
  mime:
  archive:
  js:
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
